### ISSUE TITLE
Confusion around STATE messages

### ISSUE THREAD

**Issue by robmoore** [datamill-co/target-postgres#141]
We have been attempting to use the new `STATE` message support in `target-postgres` to enable `LOG_BASED` syncing. We use `tap-postgres` as the corresponding tap and `meltano` to orchestrate the ELT process. 

What we are experiencing is captured in a [meltano](https://gitlab.com/meltano/meltano/issues/884) ticket. However, based on input from a developer on the project, it appears that the root issue is due to a difference in how this target is handling STATE versus how it is handled elsewhere. Quoting from that ticket:

> Looking at https://github.com/datamill-co/target-postgres/pull/130 it seems like they are indeed  sending the full STATE message downstream, whereas Singer themselves only write the value  out in their targets.
> See https://github.com/singer-io/target-csv/blob/a98d4633a97e3b7183a99a4f790722535b97c238/target_csv.py#L91 for target-csv example.

I'd also note that the [`singer-target-template`](https://github.com/singer-io/singer-target-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/%7B%7Bcookiecutter.package_name%7D%7D/__init__.py#L77) and [`target-gsheet`](https://github.com/singer-io/target-gsheet/blob/master/target_gsheet.py#L168) duplicate the approach taken by `target-csv`.

**Comment by awm33** [comment]
@robmoore Though the feature was added with some guidance by us, we don't use this feature since we record state at the end from a parent process, though would like to switch to using it for better partial recovery from a target failure.

I think a simple fix would be adding an output format option to the configuration.

@airhorns May have some thoughts too.

Some background on the why Data Mill don't use targets to track state (though may change):

One of the issues with STATE management is that beyond the message, there hasn't been an official spec on using it, just some examples, most not using a complex target. Stitch also doesn't really use Singer targets, it's "target" dumps the schema and records to a queue and a fairly different proprietary tech stack loads data into destinations. Not much has been thought of is using a STATE during the actual load. We also will load against different targets and track messages rather than STATE in that case. Eg with only state tracking through a target, you can't load into two different sources (like S3/Athena and Redshift using only one tap run).

**Comment by airhorns** [comment]
Crud, this stinks. Just so that we're all on the same page, the issue seems to be that `target-postgres` emits `STATE` messages differently to the other taps that emit `STATE` messages. The other taps emit the states without the wrapping `STATE: {"value": ...}` string sigil and JSON object, and I set `target-postgres` up to emit it *with* the wrapping sigil and `{"value": ...}` wrapper. 

I did that because that's what the spec says is a valid `STATE` message, see https://github.com/singer-io/getting-started/blob/master/docs/SPEC.md#example , but I guess that only applies to `STATE` messages from taps, and that the prior art for targets is to strip the surrounding hooplah. 

I think we should fall into line with the other targets, I'll prepare a PR. Sorry all!

**Comment by airhorns** [comment]
I think for what it's worth the behaviour of the other targets is indirectly documented in the singer spec by means of specify the state file contents here: https://github.com/singer-io/getting-started/blob/master/docs/CONFIG_AND_STATE.md#state-file , which as you can see, has no `{"value": ...}` wrapper. I think you're supposed to be able to write a state file by doing `tap-something | target-something > state_file.json`, so to me it's pretty clear that the `{"value": ...}` wrapper shouldn't be included in the output of `target-postgres`.
