### ISSUE TITLE
SELECT description FROM pg_description ends-up in idle in transaction

### ISSUE THREAD

**Issue by gpodevijn** [datamill-co/target-postgres#167]
Hi,

I have several tables of several hundreds of thousands of rows that I consume from a tap and pipe to target-postgres. However, after some time (in general 30/40 mins), the following query ends up in "idle in transaction": `SELECT description FROM pg_description WHERE objoid = {}::regclass;` and the "ingestion" of the data gets blocked.

I'm not really sure how to debug this. Would you have any idea how to proceed?

Thanks!

Gaëtan

**Comment by AlexanderMann** [comment]
Hey @gpodevijn! Super helpful hunting down the hanging query, thanks!

Hundreds of thousands of rows is _pretty normal_ usage given the installations I personally maintain etc.

Can you confirm that the user/connection issuing the above query is the same as the one you're using for `target-postgres`?

**Comment by AlexanderMann** [comment]
Also, can you confirm that your PostgreSQL server and host allow connections to be open for more than 30 mins? Often we see hung jobs/etc. when a gateway or something limits the lifespan of a connection.

**Comment by gpodevijn** [comment]
Hey @AlexanderMann, thanks a lot for your answer!

The user issuing the query is indeed the same as the one used for `target-postgres` (just for my knowledge, how could it be different?)

Regarding the database, It's a pretty standard Postgres on Amazon RDS with most of the default parameters.

Would you have in mind any parameters that might be worth checking?

**Comment by AlexanderMann** [comment]
@gpodevijn I wanted to confirm that the user which is _causing_ the hang is actually the single `target-postgres` process, and not some random analytics/ops/dev user also issuing conflicting transactions etc.

My experience is _usually_ that "idle in transaction" means _there's some issue with the network" etc. Especially if the time to when this happens is around the 30-40 min mark, that smacks of a timeout somewhere in your stack.

I think the suspicious part of your issue is that you're _always_ seeing it on the `describe the schema` queries.

## A _simple_ solution

I'd like to try is increasing the `max_buffer_size` in your config to something 10-100x larger than what it is right now. Why:

- we've started to see issues for other users due to this value and the fact that we originally tried to do something "clever" in computing the batch size...which is turning out to be not so clever...
- this _should_ allow the `max_batch_rows` parameter to limit the batch sizes and as it's 200K by default, your batch sizes should go up
- with larger batch sizes, you should see faster load times and might be able to get more data in under your time limit
- this will also reduce the number of times the schema detection queries will even be run

## Problem Continues

***IF*** you're still seeing the same problems in a _shorter_ amount of time, then I think we likely have a more concerning underlying issue with `Target-Postgres` and not just some random setting in a cloud-provider-of-your-choice.

## Lastly

Does the stream you're using have any `bookmarks`/`state` in it?

**Comment by gpodevijn** [comment]
@AlexanderMann I tested to increase the `max_buffer_size` but unfortunately it had no effect. I also executed the target on a local Postgres database (i.e., on the same machine as the tap). Though it seemed that the tap/target managed to process more rows and tables, it eventually failed (I still have to confirm that it's an 'idle in transaction' issue though, but I'm pretty confident it is).

For you information, the tap I'm using is [tap-zuora](https://github.com/singer-io/tap-zuora). 

I'll confirm that locally, this is the same idle in transaction issue today or tomorrow.

**Comment by AlexanderMann** [comment]
@gpodevijn that's wild. I wouldn't expect that. When you go to confirm the `idle in transaction` issue, can you also detail number of rows, and also detail how you're setting the test up locally? ie, `docker-compose`, local installation of psql, machines being used, etc.

**Comment by AlexanderMann** [comment]
@gpodevijn trying to get some work done in here this week. Is this still a problem for you? I have been running a large Target-Postgres installation with multiple writers to the given schema and haven't encountered this...

**Comment by gpodevijn** [comment]
@AlexanderMann thank you for the feedback! 

Unfortunately, we didn't make any progress on determining the root cause of this issue. The fact that you managed to do a big run makes me feel the problem was more on our side. 

We're going to test an alternative tool to ingest our data. It's safe to say that you can close this issue. 

Again, thanks a lot for your prompt responses and help.

Gaetan
