### ISSUE TITLE
Document ACTIVATION_VERSION behavior

### ISSUE THREAD

**Issue by JCotton1123** [datamill-co/target-postgres#183]
Hi,

I was hoping to get some clarification on how this target handles the activation_version messages and what the expected outcome is? I have read through the code but the intent isn't immediately obvious to me. In my own testing its creating a parent table, for example "contacts", and on subsequent runs a table for each version, example "contacts_15875...". I am trying to determine if this is expected or if its a bug or compatibility issue between the tap (Salesforce) and this target. I am happy to submit a PR with some documentation summarizing any response.

Thanks!

**Comment by AlexanderMann** [comment]
Hey @JCotton1123! 👋

So the intended behaviour for `ACTIVATE_VERSION` is actually something we inherit from the Singer spec. Some reference to that can be found here: https://github.com/singer-io/singer-python/blob/master/singer/messages.py#L137-L151

What we _expect_ to have happen, is that as data for a new `_sdc_version` comes in, we populate that to a new table which is something like what you've noted `contacts__1234...`. Once we receive an `ACTIVATE_VERSION` message, we drop the current table, and rename the `...__1234...` table to what the current one _was_.

So for your example, presumably something like: `contacts__1234` ▶️ `contacts`

## What now?

I'd recommend double checking what `tap-salesforce` is sending, as you note a couple times `ACTIVATION_VERSION`, whereas we only know about `ACTIVATE_VERSION`.

Happy to answer any additional questions!

**Comment by JCotton1123** [comment]
@AlexanderMann thanks for the response! `ACTIVATION_VERSION` is a typo, it is emitting `ACTIVATE_VERSION` messages. Given what you stated - order matters here? In other words, all record messages need to emitted before the `ACTIVATION_VERSION` message is emitted?

**Comment by AlexanderMann** [comment]
Order matters _slightly_.

So `RECORD` messages do not need to show up in a particular order. Those can come in any order they choose. However, a `SCHEMA` message ***must*** come before any `RECORD`s associated with it (otherwise we have no where to put the records).

Once an `ACTIVATE_VERSION` record shows up, we start ignoring records for earlier versions. 

If you're having trouble, you might try enabling debug logging (details in the [README](https://github.com/datamill-co/target-postgres)) and see what the logs are saying. This section of code is how the target deals with versions etc. in detail:
https://github.com/datamill-co/target-postgres/blob/master/target_postgres/postgres.py#L320-L359

**Comment by JCotton1123** [comment]
Ok, thanks for your help!
