### ISSUE TITLE
Decision - When / how to split off Redshift

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#4]
When is the best time to split off the codebase into:
- datamill-co/singer-sql-target-tools (better names welcome)
- datamill-co/target-redshift

A lot of the issues / features to be worked on overlap, but may require branching logic based on posgres vs redshift.

Is it best to do this after more work is done on postgres?

How best to do this?

**Comment by AlexanderMann** [comment]
When we do eventually do this, I'd recommend step 1 for a _pseudo_ poor implementation to be simply adding support for PSQL 8.0.2 into the postgres branch, then splitting: https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html

Obviously things like copying via s3 etc. would be...dramatically better...but I think that's for later.

Side note:
- is s3 _really_ just a different tap?

**Comment by awm33** [comment]
I think the when would ideally be in the next 1.5/2 weeks.

The how is roughly:
- Create a `target-sql-tools` repo
- Create a `target-redshift` repo
- Create a shared target class like `TargetSQL` (see redshift branch)
- Refactor / cleanup the code as it's moved to `TargetSQL`. Testing the databases differences as we go. (If we eventually target MySQL or Snowflake, we may need to break the shared functions down further, get separate generated SQL.)
- Reduce the `target-postgres` repo to postgres specific code, referencing the shared `target-sql-tools` library

Some of the above was started in the redshift branch with a rough working version.

**Comment by awm33** [comment]
@AlexanderMann ^

**Comment by AlexanderMann** [comment]
The timeframe of 2 weeks sounds fine to me. I think in order to get there/get ready for there we should potentially do something like the following:

- publish `target-postgres` on `PyPi`
  - [CD for this might be potentially quite useful](https://github.com/datamill-co/target-postgres/issues/6)
- create a `target-sql` _module_ inside of the `target-postgres` repo. Target this as another `module` in `setup.py`
- pull the `target-redshift` into the main `target-postgres` branch as another `module`, similarly target `target-sql`
  - Get testing and CI setup for this
- At the 2 week mark assess if further splitting things into distinct repos (most likely yes)

**Comment by awm33** [comment]
@AlexanderMann 

`PyPi` is not necessary for it to be included by Singer.io and many taps/targets are not published there. I'd like to get it there, but it doesn't seem like the first step or even a hard requirement to splitting the repos.

I do think starting on proper versioning makes sense to do now, we can do that using setup.py and Github tags/releases.

To fit well within the Singer community, we are going to split these into separate repos. We can stage code however we like to get to that point, but that's where it needs to be within a few weeks.

Would it make sense to stage the code splitting in a branch within this repo before the split? Otherwise the master branch is going to be thrashed around a lot before the split.

**Comment by AlexanderMann** [comment]
@awm33 

Ah, didn't realize that about that about PyPi and Singer. You know, we could also do a Docker container for this thing really easily given our current dev setup etc. (Food for thought, not advocating for tackling that over the split etc.)

Correct me if I'm wrong/not understanding your thoughts, but for _the split_ we will need PyPi right? So that both repos can rely upon the `target-sql` repo? Not sure if there's another `Python`/`git` mechanic you were thinking about here.

Versioning will be pretty straightforward. I can write up steps to do that or cut a release to get that done. Just lemme know what tickles your fancy.
------

I'm not actually so sure about how thrashed things will be...

Right now, we have what, at most 3 collaborators? We could signal the alarm that this was going to happen, let folks get in flight work into master, and then `init target-sql module`. After that, it's just pushing some files around and minor/stock and standard refactoring.

**Comment by awm33** [comment]
@AlexanderMann You're correct about ultimately needing pypi for `singer-sql-target-tools`. We can also use `dependency_links` temporarily while we build up development.

**Comment by awm33** [comment]
It feels like the when and high level how has been answered
