### ISSUE TITLE
Denesting arrays assumes items are not literals

### ISSUE THREAD

**Issue by awm33** [datamill-co/target-postgres#58]
At some points the code is assuming array items cannot be literals / scalar values. Currently it is failing to denest:

```
{
    ...
    "categories": [23, 22],
    ...
}
```

**Comment by AlexanderMann** [comment]
So this touches on a couple things:

- we need to pick a name for the column under which to put these values in the `root_table_name__categories` table
   - proposal: `root_table_name__categories: __literal`
- nested arrays of arrays are also not handled...which is a whole other bit o' fun. ie:
  - `{... 'categories': [[1, 2], [3, 4], ...] ...}` and more levels of nesting
  - To handle this, I'd propose doing:
    - `root_table_name__categories: __index__0, __index__1 ...` (or something such as)
- Another fun problem: `{type: array,  items: {type: oneOf ...}`
  - in this case, I _think_ we want to _merge_ the resulting tables, not try to postfix them with a type...I think...

**Comment by AlexanderMann** [comment]
https://github.com/datamill-co/target-postgres/pull/63 demonstrates the above.

**Comment by AlexanderMann** [comment]
# Reference
## Nested dictionaries per stitch:

> [object_name]__[property_name]__[sub_propery_name]

## Nested arrays per stitch:

Mentions `_sdc_level_n` column, but does not go in depth about what happens when n

## Literal arrays per stitch:

N/A

# Proposal

## Nested dictionaries

Handle in a similar manner to that provided by Stitch. ie, denest into parent table, make the column name long and ugly.

## Literal Arrays

Separate table. Use similar pks as to how we deal with object arrays currently. Value goes into `__value` column, index goes into `__index` column. (better prefix desired, but don't want to use `sdc` like everything else as this is _not_ a `sdc` thing)

## Nested Arrays

Similar handling to literal arrays. Continue de-nesting values, making long ugly tables with names like:

`root__nested_array_column____value____value____value` etc.

**Comment by AlexanderMann** [comment]
Per Stitch:

> Arrays of literals are treated the same as arrays of objects _except_ the values in the array will be denested into a `value` column` and the index of the value will be placed in the `_sdc_level_<n>_id`

@awm33 I might still propose that we tuck values into somthing like `_sdc_value` etc. (choose your prefix etc.)

**Comment by AlexanderMann** [comment]
@awm33 this pr now has fixes for _some_ of the known bugs: https://github.com/datamill-co/target-postgres/pull/63

The only one which is remaining, is defaulting for arrays or objects. This is _probably_ reasonable to leave as feature work.

**Comment by AlexanderMann** [comment]
@awm33 another bug which is not presently covered is multiple types for a column in a single batch. Getting the upserting of the schema functionality to work was quite straightforward, but getting the denesting to be able to handle splitting values between things is not yet so straightforward.

I can tackle this today, but I could also see this as being something to push to post v0.

**Comment by awm33** [comment]
@AlexanderMann For the prefix, that's tough. I'm guessing the thinking was `_sdc_*` are metadata columns where this is an actual data value? Though `_sdc_*` could mean any synthesized column. `value` will be no where in the original schema. Lets add the prefix.

**Comment by AlexanderMann** [comment]
@awm33 to clarify, you _specifically_ mean make literal values into `_sdc_value` correct?

**Comment by awm33** [comment]
@AlexanderMann Yes
